### ISSUE TITLE
`Num` constraint is redundant on divRem/divRem32

### ISSUE THREAD

**Issue by chessai** [goolord/atrophy#5]
in `divRem`, `a` is marked as `Integral`, which is a subclass of `Num`
in `divRem32`, both `a` and `b` are marked as Integral, which is a subclass of `Num`

**Comment by chessai** [comment]
Also redundant on `t` in `new`

**Comment by goolord** [comment]
fixed in https://github.com/goolord/atrophy/commit/29252b3a82d778a3bca6398e9818a01aa6469020
