### ISSUE TITLE
StrengthReduced types: No need to use `Multiplier` type family

### ISSUE THREAD

**Issue by chessai** [goolord/atrophy#7]
the types these resolve to are static, and using a type family can mess with coercions. Might as well just substitute for what they evaluate to

**Comment by goolord** [comment]
yeah that's true, it's not like it's going to change. it was helpful while writing the library, tho

**Comment by goolord** [comment]
https://github.com/goolord/atrophy/commit/ad5a844482a77791aa0797968e83598c18abaf17
